apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
        - name: portfolio-app
          image: us-central1-docker.pkg.dev/cloud-portfolio-1/portfolio-repo/portfolio-app:latest
          ports:
            - containerPort: 80
