name: CD - Build, Push, Deploy to GKE

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write   # REQUIRED for Workload Identity Federation

env:
  PROJECT_ID: cloud-portfolio-1
  PROJECT_NUMBER: "714816545825"
  REGION: us-central1
  CLUSTER_NAME: portfolio-cluster
  CLUSTER_ZONE: us-central1-a
  AR_REPO: portfolio-repo
  IMAGE_NAME: portfolio-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/714816545825/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gha-deployer@cloud-portfolio-1.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push image to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
     

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to GKE (kubectl apply)
        run: |
          kubectl create namespace portfolio --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n portfolio apply -f k8s/

      - name: Update image (forces rollout)
        run: |
          kubectl -n portfolio set image deployment/portfolio-app portfolio-app=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          kubectl -n portfolio rollout status deployment/portfolio-app
